#Application Url
url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

#Browser configuration
browser = chrome

#Credentials
username = admin
password = admin123

#ImplicitWait (in seconds)
implicitWait = 10

#Explicit Wait
explicitWait = 30